import { BRAND } from '../i18n/constants';
import { tstr } from './typst-str';
import type { LangSetting } from './lang';
import type { FontSet } from '../typst/fonts';

export { SUPPORTED_LANGUAGES, type LangSetting, type LangCode } from './lang';

export type PaperSize = 'a4' | 'us-letter' | 'a5' | 'iso-b5';

/** Page templates; what each one does is in src/layout/templates.ts. */
export type TemplateId = 'default' | 'report' | 'academic' | 'resume' | 'letter';
export const TEMPLATE_IDS: readonly TemplateId[] = ['default', 'report', 'academic', 'resume', 'letter'];

export interface DocumentOptions {
  paper: PaperSize;
  /** Page margin in millimetres. */
  margin: number;
  /** Body font size in points. */
  fontSize: number;
  /** Multiple of font size used for leading. */
  lineHeight: number;
  pageNumbers: boolean;
  tableOfContents: boolean;
  justify: boolean;
  title: string;
  author: string;
  /**
   * Document language: `auto` detects it from the text. Drives hyphenation,
   * line breaking, quote marks, text direction, Han glyph forms and the table
   * of contents title. See `SUPPORTED_LANGUAGES` for the values.
   */
  lang: LangSetting;
  /** Table of contents title; empty means the language's usual word. */
  tocTitle: string;
  /** Page template (src/layout/templates.ts). YAML front matter can override this and most options. */
  template: TemplateId;
  /** A title page from the title, subtitle, author and date; it has no header or footer. */
  cover: boolean;
  /** Start every level-1 heading on a new page. */
  h1NewPage: boolean;
  /**
   * Running header and footer. Tokens: {title} {page} {pages} {date} {author};
   * `|` splits left | centre | right. Empty means the template's own ("{page} /
   * {pages}" for the footer when page numbers are on); `none` means nothing.
   */
  header: string;
  footer: string;
}

export const DEFAULT_OPTIONS: DocumentOptions = {
  paper: 'a4',
  margin: 20,
  fontSize: 11,
  lineHeight: 1.6,
  pageNumbers: true,
  tableOfContents: false,
  justify: true,
  title: '',
  author: '',
  lang: 'auto',
  tocTitle: '',
  template: 'default',
  cover: false,
  h1NewPage: false,
  header: '',
  footer: '',
};

/**
 * The body font list: Noto Sans (or Noto Serif for a serif template), then
 * every family the document loaded, in order. In Chinese and Japanese, quotes,
 * ellipses and dashes are full-width and must come from the CJK face, although
 * the Latin face has them too; Typst's `latin-in-cjk` leaves exactly those to
 * the next font. `bold` leaves out faces that only have a regular weight (the
 * serif CJK faces: bold CJK is set in the sans face, as is conventional).
 */
export function bodyFonts(fonts: FontSet, bold = false): string {
  const cjkPunctuation = fonts.lang.cjkPunctuation && fonts.families.some(f => f.cjk);
  // Noto Sans stays behind Noto Serif for the symbols the serif face lacks.
  const latin = (fonts.serif ? ['Noto Serif', 'Noto Sans'] : ['Noto Sans']).map(name =>
    cjkPunctuation ? `(name: ${tstr(name)}, covers: "latin-in-cjk")` : tstr(name),
  );
  const families = fonts.families.filter(f => !(bold && f.regularOnly));
  return `(${[...latin, ...families.map(f => tstr(f.family))].join(', ')})`;
}

/**
 * Helper definitions the emitter relies on, plus document-wide styling. Keeping
 * the styling here (rather than inlining it at every call site) keeps generated
 * sources small and readable when a user exports the Typst source.
 */
export function buildPreamble(options: DocumentOptions, fonts: FontSet, extra = ''): string {
  const lang = fonts.lang;
  const hasCjkFace = fonts.families.some(f => f.cjk);
  const cjkPunctuation = lang.cjkPunctuation && hasCjkFace;
  const body = bodyFonts(fonts);
  const mono = `(${['"DejaVu Sans Mono"', ...fonts.families.map(f => tstr(f.family)), '"Noto Sans"'].join(', ')})`;
  const region = lang.region ? `, region: ${tstr(lang.region)}` : '';
  const rtl = lang.dir === 'rtl';
  // Typst cannot justify Thai, which has no spaces between words: it would
  // stretch the few spaces between phrases instead.
  const justify = options.justify && lang.code !== 'th';
  // Corner brackets are the standard quotes in Japanese and in Taiwan.
  const quotes =
    lang.code === 'ja' || lang.code === 'zh-Hant'
      ? '#set smartquote(quotes: (single: "『』", double: "「」"))\n'
      : '';
  const tocTitle = options.tocTitle?.trim() || lang.tocTitle;
  // Leading is the gap between lines, so subtract the line itself.
  const leading = Math.max(0.1, options.lineHeight - 1).toFixed(3);

  const numbering = options.pageNumbers ? `numbering: "1", number-align: center,` : '';
  const docMeta = [
    options.title ? `title: ${tstr(options.title)}` : '',
    options.author ? `author: ${tstr(options.author)}` : '',
  ]
    .filter(Boolean)
    .join(', ');

  const side = rtl ? 'right' : 'left';
  return `// Generated by ${BRAND} — everything below is plain Typst.
#set document(${docMeta})
#set page(paper: ${tstr(options.paper)}, margin: ${options.margin}mm, ${numbering})
// Language ${lang.code}${lang.detected ? ' (detected)' : ''}: hyphenation, line breaking, quotes, direction.
#set text(font: ${body}, size: ${options.fontSize}pt, lang: ${tstr(lang.typstLang)}${region})
#set par(justify: ${justify}, leading: ${leading}em, spacing: 1.2em)
${quotes}#let md-apos = ${cjkPunctuation ? `text(font: ${fonts.serif ? '"Noto Serif"' : '"Noto Sans"'}, "\u{2019}")` : '"\u{2019}"'}
#set heading(numbering: none)
#show heading: it => block(above: 1.4em, below: 0.7em, it)
#show heading.where(level: 1): set text(size: 1.7em)
#show heading.where(level: 2): set text(size: 1.35em)
#show heading.where(level: 3): set text(size: 1.15em)
#show link: set text(fill: rgb("#1a1a1a"))
#set underline(offset: 2pt)
#show link: underline

#let md-mono-font = ${mono}
#show raw: set text(font: md-mono-font, size: 0.88em${rtl ? ', dir: ltr' : ''})${rtl ? '\n#show raw.where(block: true): set align(left)' : ''}
#show raw.where(block: true): it => block(
  width: 100%,
  fill: rgb("#f6f6f6"),
  stroke: 0.5pt + rgb("#dcdcdc"),
  radius: 4pt,
  inset: (x: 10pt, y: 8pt),
  it,
)
#show raw.where(block: false): it => box(
  fill: rgb("#f2f2f2"),
  outset: (y: 3pt),
  inset: (x: 3pt),
  radius: 2pt,
  it,
)

#let md-quote(body) = block(
  width: 100%,
  inset: (${side}: 12pt, rest: 6pt),
  stroke: (${side}: 3pt + rgb("#d4d4d4")),
  text(fill: rgb("#5c5c5c"), body),
)
#let md-rule() = align(center, line(length: 100%, stroke: 0.5pt + rgb("#d4d4d4")))
#let md-task(done) = box(
  baseline: 2pt,
  inset: (${rtl ? 'left' : 'right'}: 3pt),
  text(font: ("DejaVu Sans Mono"), if done { "[x]" } else { "[ ]" }),
)
#let md-figure(body, caption) = figure(body, caption: caption)
#set figure(gap: 0.8em)
#show figure.caption: set text(size: 0.9em, fill: rgb("#5c5c5c"))
#set table(stroke: 0.5pt + rgb("#d4d4d4"), inset: 7pt)
#show table.cell.where(y: 0): strong
${extra}
${options.tableOfContents ? `#outline(title: [#${tstr(tocTitle)}], depth: 3)\n#pagebreak()\n` : ''}`;
}

/** Where the vendored mitex spec is mapped in the compiler's shadow filesystem. */
export const MATH_SPEC_PATH = '/md2pdf-math/latex/standard.typ';

/**
 * Maths support, added to the preamble only when a document has formulas
 * (passed as `extra` above, so it precedes the table of contents, whose
 * entries may contain maths).
 *
 * Each formula arrives as a string literal holding Typst maths markup that
 * mitex produced and `src/math/typst-math.ts` validated. It is parsed by
 * `eval` in maths mode, in isolation from the document, with mitex's helper
 * functions in scope; see that file for why this is safe.
 */
export function buildMathPreamble(): string {
  return `
#show math.equation: set text(font: "Noto Sans Math")
#import "${MATH_SPEC_PATH}": package as md-mitex
#let md-math(id, display, code) = math.equation(
  block: display,
  eval(mode: "math", code, scope: md-mitex.scope),
)
#let md-math-error(display, source, message) = {
  let body = text(fill: rgb("#fa0f00"))[#raw(source) #text(size: 0.8em)[(#message)]]
  if display {
    block(width: 100%, inset: (x: 8pt, y: 6pt), fill: rgb("#fff0ef"), stroke: (left: 2pt + rgb("#fa0f00")), body)
  } else {
    box(body)
  }
}
`;
}
