import { tstr } from './typst-str';

export type PaperSize = 'a4' | 'us-letter' | 'a5' | 'iso-b5';

export interface DocumentOptions {
  paper: PaperSize;
  /** Page margin in millimetres. */
  margin: number;
  /** Body font size in points. */
  fontSize: number;
  /** Multiple of font size used for leading. */
  lineHeight: number;
  pageNumbers: boolean;
  tableOfContents: boolean;
  justify: boolean;
  title: string;
  author: string;
}

export const DEFAULT_OPTIONS: DocumentOptions = {
  paper: 'a4',
  margin: 20,
  fontSize: 11,
  lineHeight: 1.6,
  pageNumbers: true,
  tableOfContents: false,
  justify: true,
  title: '',
  author: '',
};

/**
 * Helper definitions the emitter relies on, plus document-wide styling. Keeping
 * the styling here (rather than inlining it at every call site) keeps generated
 * sources small and readable when a user exports the Typst source.
 */
export function buildPreamble(options: DocumentOptions, hasCjk: boolean): string {
  const serif = hasCjk ? `("Libertinus Serif", "Noto Sans SC")` : `("Libertinus Serif")`;
  const mono = hasCjk ? `("DejaVu Sans Mono", "Noto Sans SC")` : `("DejaVu Sans Mono")`;
  const lang = hasCjk ? 'zh' : 'en';
  // Leading is the gap between lines, so subtract the line itself.
  const leading = Math.max(0.1, options.lineHeight - 1).toFixed(3);

  const numbering = options.pageNumbers ? `numbering: "1", number-align: center,` : '';
  const docMeta = [
    options.title ? `title: ${tstr(options.title)}` : '',
    options.author ? `author: ${tstr(options.author)}` : '',
  ]
    .filter(Boolean)
    .join(', ');

  return `// Generated by md2pdf — everything below is plain Typst.
#set document(${docMeta})
#set page(paper: ${tstr(options.paper)}, margin: ${options.margin}mm, ${numbering})
#set text(font: ${serif}, size: ${options.fontSize}pt, lang: ${tstr(lang)})
#set par(justify: ${options.justify}, leading: ${leading}em, spacing: 1.2em)
#set heading(numbering: none)
#show heading: it => block(above: 1.4em, below: 0.7em, it)
#show heading.where(level: 1): set text(size: 1.7em)
#show heading.where(level: 2): set text(size: 1.35em)
#show heading.where(level: 3): set text(size: 1.15em)
#show link: set text(fill: rgb("#0b62c4"))
#set underline(offset: 2pt)
#show link: underline

#let md-mono-font = ${mono}
#show raw: set text(font: md-mono-font, size: 0.88em)
#show raw.where(block: true): it => block(
  width: 100%,
  fill: rgb("#f6f8fa"),
  stroke: 0.5pt + rgb("#d8dee4"),
  radius: 4pt,
  inset: (x: 10pt, y: 8pt),
  it,
)
#show raw.where(block: false): it => box(
  fill: rgb("#f2f3f5"),
  outset: (y: 3pt),
  inset: (x: 3pt),
  radius: 2pt,
  it,
)

#let md-quote(body) = block(
  width: 100%,
  inset: (left: 12pt, rest: 6pt),
  stroke: (left: 3pt + rgb("#d0d7de")),
  text(fill: rgb("#57606a"), body),
)
#let md-rule() = align(center, line(length: 100%, stroke: 0.5pt + rgb("#d0d7de")))
#let md-task(done) = box(
  baseline: 2pt,
  inset: (right: 3pt),
  text(font: ("DejaVu Sans Mono"), if done { "[x]" } else { "[ ]" }),
)
#let md-figure(body, caption) = figure(body, caption: caption)
#set figure(gap: 0.8em)
#show figure.caption: set text(size: 0.9em, fill: rgb("#57606a"))
#set table(stroke: 0.5pt + rgb("#d0d7de"), inset: 7pt)
#show table.cell.where(y: 0): strong

${options.tableOfContents ? '#outline(title: [' + (hasCjk ? '目录' : 'Contents') + '], depth: 3)\n#pagebreak()\n' : ''}`;
}
