import { chromium } from 'playwright';
import { CHROMIUM, waitForConversion } from './app-helpers.mjs';
const OUT = '/tmp/claude-0/-home-user-md2pdf/145ae161-a9f8-50b2-82c8-be6dc82893f1/scratchpad';
const b = await chromium.launch({ executablePath: CHROMIUM });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto(process.env.APP_URL, { waitUntil: 'load' });
await p.waitForSelector('.cm-content', { timeout: 30000 });
await p.screenshot({ path: `${OUT}/shot-idle.png` });
await p.click('#convert');
await waitForConversion(p);
await p.waitForSelector('.page canvas');
await p.screenshot({ path: `${OUT}/shot-app.png` });
await p.evaluate(() => document.querySelector('.about').scrollIntoView());
await p.waitForTimeout(400);
await p.screenshot({ path: `${OUT}/shot-about.png` });
await b.close();
